### ISSUE TITLE
tip: css property shorthand

### ISSUE THREAD

**Issue by ZakkMan** [HannahAurand/hannahaurand.github.io#7]
You can use the CSS property shorthand here.

This:

https://github.com/HannahAurand/hannahaurand.github.io/blob/588dcd3c9ab3d6fc2ac224b8646061d63ffe30ce/CSS/mainStyle.css#L4-L8

Could be:

```css
 body { 
     margin: 0;
 } 
```
